// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302112102_FullERD")]
    partial class FullERD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("WebApplication1.Models.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbilityTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AbilityTypeId");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("WebApplication1.Models.AbilityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AbilityTypes");
                });

            modelBuilder.Entity("WebApplication1.Models.ArmorStats", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Durability")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("ArmorStats");
                });

            modelBuilder.Entity("WebApplication1.Models.AttributeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AttributeDefinitions");
                });

            modelBuilder.Entity("WebApplication1.Models.Beruf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Berufe");
                });

            modelBuilder.Entity("WebApplication1.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BerufId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReligionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VolkId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BerufId");

                    b.HasIndex("InventoryId")
                        .IsUnique();

                    b.HasIndex("RaceId");

                    b.HasIndex("ReligionId");

                    b.HasIndex("VolkId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("WebApplication1.Models.CharacterAbility", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbilityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "AbilityId");

                    b.HasIndex("AbilityId");

                    b.ToTable("CharacterAbilities");
                });

            modelBuilder.Entity("WebApplication1.Models.ConsumableStats", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cooldown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Effect")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("ConsumableStats");
                });

            modelBuilder.Entity("WebApplication1.Models.Fraktion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeltId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WeltId");

                    b.ToTable("Fraktionen");
                });

            modelBuilder.Entity("WebApplication1.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("WebApplication1.Models.InventoryItem", b =>
                {
                    b.Property<int>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("InventoryId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("WebApplication1.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<float>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("WebApplication1.Models.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ItemTypes");
                });

            modelBuilder.Entity("WebApplication1.Models.Kampf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Kämpfe");
                });

            modelBuilder.Entity("WebApplication1.Models.KampfLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AngreiferId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KampfId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rolled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("VerteidigerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AngreiferId");

                    b.HasIndex("KampfId");

                    b.HasIndex("VerteidigerId");

                    b.ToTable("KampfLogs");
                });

            modelBuilder.Entity("WebApplication1.Models.KampfTeilnehmer", b =>
                {
                    b.Property<int>("KampfId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Initiative")
                        .HasColumnType("INTEGER");

                    b.HasKey("KampfId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("KampfTeilnehmer");
                });

            modelBuilder.Entity("WebApplication1.Models.Ort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeltId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WeltId");

                    b.ToTable("Orte");
                });

            modelBuilder.Entity("WebApplication1.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("WebApplication1.Models.Religion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Religionen");
                });

            modelBuilder.Entity("WebApplication1.Models.Volk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Völker");
                });

            modelBuilder.Entity("WebApplication1.Models.WeaponStats", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Durability")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeaponType")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("WeaponStats");
                });

            modelBuilder.Entity("WebApplication1.Models.Welt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Welten");
                });

            modelBuilder.Entity("WebApplication1.Models.Ability", b =>
                {
                    b.HasOne("WebApplication1.Models.AbilityType", "AbilityType")
                        .WithMany("Abilities")
                        .HasForeignKey("AbilityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbilityType");
                });

            modelBuilder.Entity("WebApplication1.Models.ArmorStats", b =>
                {
                    b.HasOne("WebApplication1.Models.Item", "Item")
                        .WithOne("ArmorStats")
                        .HasForeignKey("WebApplication1.Models.ArmorStats", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WebApplication1.Models.Character", b =>
                {
                    b.HasOne("WebApplication1.Models.Beruf", "Beruf")
                        .WithMany("Characters")
                        .HasForeignKey("BerufId");

                    b.HasOne("WebApplication1.Models.Inventory", "Inventory")
                        .WithOne()
                        .HasForeignKey("WebApplication1.Models.Character", "InventoryId");

                    b.HasOne("WebApplication1.Models.Race", "Race")
                        .WithMany("Characters")
                        .HasForeignKey("RaceId");

                    b.HasOne("WebApplication1.Models.Religion", "Religion")
                        .WithMany("Characters")
                        .HasForeignKey("ReligionId");

                    b.HasOne("WebApplication1.Models.Volk", "Volk")
                        .WithMany("Characters")
                        .HasForeignKey("VolkId");

                    b.Navigation("Beruf");

                    b.Navigation("Inventory");

                    b.Navigation("Race");

                    b.Navigation("Religion");

                    b.Navigation("Volk");
                });

            modelBuilder.Entity("WebApplication1.Models.CharacterAbility", b =>
                {
                    b.HasOne("WebApplication1.Models.Ability", "Ability")
                        .WithMany("CharacterAbilities")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Character", "Character")
                        .WithMany("Abilities")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("WebApplication1.Models.ConsumableStats", b =>
                {
                    b.HasOne("WebApplication1.Models.Item", "Item")
                        .WithOne("ConsumableStats")
                        .HasForeignKey("WebApplication1.Models.ConsumableStats", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WebApplication1.Models.Fraktion", b =>
                {
                    b.HasOne("WebApplication1.Models.Welt", "Welt")
                        .WithMany("Fraktionen")
                        .HasForeignKey("WeltId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Welt");
                });

            modelBuilder.Entity("WebApplication1.Models.InventoryItem", b =>
                {
                    b.HasOne("WebApplication1.Models.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Item", "Item")
                        .WithMany("InventoryItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WebApplication1.Models.Item", b =>
                {
                    b.HasOne("WebApplication1.Models.ItemType", "ItemType")
                        .WithMany()
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("WebApplication1.Models.KampfLog", b =>
                {
                    b.HasOne("WebApplication1.Models.Character", "Angreifer")
                        .WithMany()
                        .HasForeignKey("AngreiferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Kampf", "Kampf")
                        .WithMany("Logs")
                        .HasForeignKey("KampfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Character", "Verteidiger")
                        .WithMany()
                        .HasForeignKey("VerteidigerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Angreifer");

                    b.Navigation("Kampf");

                    b.Navigation("Verteidiger");
                });

            modelBuilder.Entity("WebApplication1.Models.KampfTeilnehmer", b =>
                {
                    b.HasOne("WebApplication1.Models.Character", "Character")
                        .WithMany("KampfTeilnehmer")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Kampf", "Kampf")
                        .WithMany("Teilnehmer")
                        .HasForeignKey("KampfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Kampf");
                });

            modelBuilder.Entity("WebApplication1.Models.Ort", b =>
                {
                    b.HasOne("WebApplication1.Models.Welt", "Welt")
                        .WithMany("Orte")
                        .HasForeignKey("WeltId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Welt");
                });

            modelBuilder.Entity("WebApplication1.Models.WeaponStats", b =>
                {
                    b.HasOne("WebApplication1.Models.Item", "Item")
                        .WithOne("WeaponStats")
                        .HasForeignKey("WebApplication1.Models.WeaponStats", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WebApplication1.Models.Ability", b =>
                {
                    b.Navigation("CharacterAbilities");
                });

            modelBuilder.Entity("WebApplication1.Models.AbilityType", b =>
                {
                    b.Navigation("Abilities");
                });

            modelBuilder.Entity("WebApplication1.Models.Beruf", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("WebApplication1.Models.Character", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("KampfTeilnehmer");
                });

            modelBuilder.Entity("WebApplication1.Models.Inventory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WebApplication1.Models.Item", b =>
                {
                    b.Navigation("ArmorStats");

                    b.Navigation("ConsumableStats");

                    b.Navigation("InventoryItems");

                    b.Navigation("WeaponStats");
                });

            modelBuilder.Entity("WebApplication1.Models.Kampf", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Teilnehmer");
                });

            modelBuilder.Entity("WebApplication1.Models.Race", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("WebApplication1.Models.Religion", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("WebApplication1.Models.Volk", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("WebApplication1.Models.Welt", b =>
                {
                    b.Navigation("Fraktionen");

                    b.Navigation("Orte");
                });
#pragma warning restore 612, 618
        }
    }
}
